In [23]:
# import libraries
import pandas as pd
import numpy as np
import seaborn as sns

In [24]:
#read dataset
df = pd.read_csv('../Data/originalData/brain_tumor_dataset.csv')
df

,Patient_ID,Age,Gender,Tumor_Type,Tumor_Size,Location,Histology,Stage,Symptom_1,Symptom_2,Symptom_3,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,MRI_Result,Follow_Up_Required
0,1,73,Male,Malignant,5.375612,Temporal,Astrocytoma,III,Vision Issues,Seizures,Seizures,No,No,No,51.312579,0.111876,No,Positive,Yes
1,2,26,Male,Benign,4.847098,Parietal,Glioblastoma,II,Headache,Headache,Nausea,Yes,Yes,Yes,46.373273,2.165736,Yes,Positive,Yes
2,3,31,Male,Benign,5.588391,Parietal,Meningioma,I,Vision Issues,Headache,Seizures,No,No,No,47.072221,1.884228,No,Negative,No
3,4,29,Male,Malignant,1.436600,Temporal,Medulloblastoma,IV,Vision Issues,Seizures,Headache,Yes,No,Yes,51.853634,1.283342,Yes,Negative,No
4,5,54,Female,Benign,2.417506,Parietal,Glioblastoma,I,Headache,Headache,Seizures,No,No,Yes,54.708987,2.069477,No,Positive,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,21,Male,Malignant,9.612013,Parietal,Medulloblastoma,III,Seizures,Nausea,Vision Issues,No,No,Yes,58.229662,0.353806,No,Negative,Yes
19996,19997,32,Female,Benign,1.543560,Temporal,Meningioma,III,Headache,Headache,Vision Issues,Yes,Yes,No,77.706856,2.341074,No,Positive,No
19997,19998,57,Female,Benign,3.618634,Temporal,Medulloblastoma,I,Seizures,Vision Issues,Nausea,No,No,Yes,89.543803,2.332881,No,Positive,Yes
19998,19999,68,Male,Malignant,8.519086,Parietal,Glioblastoma,III,Seizures,Headache,Vision Issues,Yes,Yes,Yes,83.306781,2.387202,No,Positive,No
19999,20000,61,Male,Benign,9.716768,Temporal,Medulloblastoma,I,Vision Issues,Seizures,Nausea,No,No,No,47.433468,2.464077,Yes,Negative,Yes

## Remove Cols

In [25]:
# we dont need patent ID since it's just and index
df = df.drop(columns=['Patient_ID'])
df

,Age,Gender,Tumor_Type,Tumor_Size,Location,Histology,Stage,Symptom_1,Symptom_2,Symptom_3,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,MRI_Result,Follow_Up_Required
0,73,Male,Malignant,5.375612,Temporal,Astrocytoma,III,Vision Issues,Seizures,Seizures,No,No,No,51.312579,0.111876,No,Positive,Yes
1,26,Male,Benign,4.847098,Parietal,Glioblastoma,II,Headache,Headache,Nausea,Yes,Yes,Yes,46.373273,2.165736,Yes,Positive,Yes
2,31,Male,Benign,5.588391,Parietal,Meningioma,I,Vision Issues,Headache,Seizures,No,No,No,47.072221,1.884228,No,Negative,No
3,29,Male,Malignant,1.436600,Temporal,Medulloblastoma,IV,Vision Issues,Seizures,Headache,Yes,No,Yes,51.853634,1.283342,Yes,Negative,No
4,54,Female,Benign,2.417506,Parietal,Glioblastoma,I,Headache,Headache,Seizures,No,No,Yes,54.708987,2.069477,No,Positive,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,21,Male,Malignant,9.612013,Parietal,Medulloblastoma,III,Seizures,Nausea,Vision Issues,No,No,Yes,58.229662,0.353806,No,Negative,Yes
19996,32,Female,Benign,1.543560,Temporal,Meningioma,III,Headache,Headache,Vision Issues,Yes,Yes,No,77.706856,2.341074,No,Positive,No
19997,57,Female,Benign,3.618634,Temporal,Medulloblastoma,I,Seizures,Vision Issues,Nausea,No,No,Yes,89.543803,2.332881,No,Positive,Yes
19998,68,Male,Malignant,8.519086,Parietal,Glioblastoma,III,Seizures,Headache,Vision Issues,Yes,Yes,Yes,83.306781,2.387202,No,Positive,No
19999,61,Male,Benign,9.716768,Temporal,Medulloblastoma,I,Vision Issues,Seizures,Nausea,No,No,No,47.433468,2.464077,Yes,Negative,Yes

In [26]:
## check nulls one more time
df.isna().sum()

Age                    0
Gender                 0
Tumor_Type             0
Tumor_Size             0
Location               0
Histology              0
Stage                  0
Symptom_1              0
Symptom_2              0
Symptom_3              0
Radiation_Treatment    0
Surgery_Performed      0
Chemotherapy           0
Survival_Rate          0
Tumor_Growth_Rate      0
Family_History         0
MRI_Result             0
Follow_Up_Required     0
dtype: int64

## Encode values

In [27]:
# count non num columns
non_num_col = df.select_dtypes(include=['object']).columns

# print the number of string columns
print(len(non_num_col))

#print the non num col
non_num_col

14

Index(['Gender', 'Tumor_Type', 'Location', 'Histology', 'Stage', 'Symptom_1',
       'Symptom_2', 'Symptom_3', 'Radiation_Treatment', 'Surgery_Performed',
       'Chemotherapy', 'Family_History', 'MRI_Result', 'Follow_Up_Required'],
      dtype='object')

we want to one hot encode non ordered categories and label encode the rest like

In [28]:
# encode cols
df = pd.get_dummies(df, columns=[
    'Gender', 'Location', 'Histology', 
    'Symptom_1', 'Symptom_2', 'Symptom_3'
], drop_first=True)
df

,Age,Tumor_Type,Tumor_Size,Stage,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,...,Histology_Meningioma,Symptom_1_Nausea,Symptom_1_Seizures,Symptom_1_Vision Issues,Symptom_2_Nausea,Symptom_2_Seizures,Symptom_2_Vision Issues,Symptom_3_Nausea,Symptom_3_Seizures,Symptom_3_Vision Issues
0,73,Malignant,5.375612,III,No,No,No,51.312579,0.111876,No,...,False,False,False,True,False,True,False,False,True,False
1,26,Benign,4.847098,II,Yes,Yes,Yes,46.373273,2.165736,Yes,...,False,False,False,False,False,False,False,True,False,False
2,31,Benign,5.588391,I,No,No,No,47.072221,1.884228,No,...,True,False,False,True,False,False,False,False,True,False
3,29,Malignant,1.436600,IV,Yes,No,Yes,51.853634,1.283342,Yes,...,False,False,False,True,False,True,False,False,False,False
4,54,Benign,2.417506,I,No,No,Yes,54.708987,2.069477,No,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,21,Malignant,9.612013,III,No,No,Yes,58.229662,0.353806,No,...,False,False,True,False,True,False,False,False,False,True
19996,32,Benign,1.543560,III,Yes,Yes,No,77.706856,2.341074,No,...,True,False,False,False,False,False,False,False,False,True
19997,57,Benign,3.618634,I,No,No,Yes,89.543803,2.332881,No,...,False,False,True,False,False,False,True,True,False,False
19998,68,Malignant,8.519086,III,Yes,Yes,Yes,83.306781,2.387202,No,...,False,False,True,False,False,False,False,False,False,True
19999,61,Benign,9.716768,I,No,No,No,47.433468,2.464077,Yes,...,False,False,False,True,False,True,False,True,False,False

In [29]:
# label encoding for the rest
binary_cols = ['Tumor_Type', 'Radiation_Treatment', 'Surgery_Performed', 
               'Chemotherapy', 'Family_History', 'MRI_Result', 'Follow_Up_Required']

for col in binary_cols:
    df[col] = df[col].map({'Yes':1, 'No':0, 'Positive':1, 'Negative':0, 'Malignant':1, 'Benign':0})

# Stage: I â†’ 1, II â†’ 2, III â†’ 3, IV â†’ 4
stage_mapping = {'I':1, 'II':2, 'III':3, 'IV':4}
df['Stage'] = df['Stage'].map(stage_mapping)

In [30]:
df

,Age,Tumor_Type,Tumor_Size,Stage,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,...,Histology_Meningioma,Symptom_1_Nausea,Symptom_1_Seizures,Symptom_1_Vision Issues,Symptom_2_Nausea,Symptom_2_Seizures,Symptom_2_Vision Issues,Symptom_3_Nausea,Symptom_3_Seizures,Symptom_3_Vision Issues
0,73,1,5.375612,3,0,0,0,51.312579,0.111876,0,...,False,False,False,True,False,True,False,False,True,False
1,26,0,4.847098,2,1,1,1,46.373273,2.165736,1,...,False,False,False,False,False,False,False,True,False,False
2,31,0,5.588391,1,0,0,0,47.072221,1.884228,0,...,True,False,False,True,False,False,False,False,True,False
3,29,1,1.436600,4,1,0,1,51.853634,1.283342,1,...,False,False,False,True,False,True,False,False,False,False
4,54,0,2.417506,1,0,0,1,54.708987,2.069477,0,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,21,1,9.612013,3,0,0,1,58.229662,0.353806,0,...,False,False,True,False,True,False,False,False,False,True
19996,32,0,1.543560,3,1,1,0,77.706856,2.341074,0,...,True,False,False,False,False,False,False,False,False,True
19997,57,0,3.618634,1,0,0,1,89.543803,2.332881,0,...,False,False,True,False,False,False,True,True,False,False
19998,68,1,8.519086,3,1,1,1,83.306781,2.387202,0,...,False,False,True,False,False,False,False,False,False,True
19999,61,0,9.716768,1,0,0,0,47.433468,2.464077,1,...,False,False,False,True,False,True,False,True,False,False

In [31]:
# convert all t/f to 1/0
df = df.astype({col: int for col in df.columns if df[col].dtype == 'bool'})
df

,Age,Tumor_Type,Tumor_Size,Stage,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,...,Histology_Meningioma,Symptom_1_Nausea,Symptom_1_Seizures,Symptom_1_Vision Issues,Symptom_2_Nausea,Symptom_2_Seizures,Symptom_2_Vision Issues,Symptom_3_Nausea,Symptom_3_Seizures,Symptom_3_Vision Issues
0,73,1,5.375612,3,0,0,0,51.312579,0.111876,0,...,0,0,0,1,0,1,0,0,1,0
1,26,0,4.847098,2,1,1,1,46.373273,2.165736,1,...,0,0,0,0,0,0,0,1,0,0
2,31,0,5.588391,1,0,0,0,47.072221,1.884228,0,...,1,0,0,1,0,0,0,0,1,0
3,29,1,1.436600,4,1,0,1,51.853634,1.283342,1,...,0,0,0,1,0,1,0,0,0,0
4,54,0,2.417506,1,0,0,1,54.708987,2.069477,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,21,1,9.612013,3,0,0,1,58.229662,0.353806,0,...,0,0,1,0,1,0,0,0,0,1
19996,32,0,1.543560,3,1,1,0,77.706856,2.341074,0,...,1,0,0,0,0,0,0,0,0,1
19997,57,0,3.618634,1,0,0,1,89.543803,2.332881,0,...,0,0,1,0,0,0,1,1,0,0
19998,68,1,8.519086,3,1,1,1,83.306781,2.387202,0,...,0,0,1,0,0,0,0,0,0,1
19999,61,0,9.716768,1,0,0,0,47.433468,2.464077,1,...,0,0,0,1,0,1,0,1,0,0

## Feature Scaling and normalization